# Commands to start when Gitpod spins up
tasks:
  - before: docker build -f Dockerfile . -t nginxsite:dev
    init: docker run -d -p 0.0.0.0:8000:80 nginxsite:dev
ports:
  - port: 8000
    onOpen: open-preview
