# Commands to start when Gitpod spins up
tasks:
  - init: docker
    command: build . --file Dockerfile --tag nginx-site:dev-$(date +%s)
  - init: docker
    command: run -d nginx-site:dev-$(date +%s) -p 80:80

ports:
  - port: 80
    onOpen: open-preview