# Commands to start when Gitpod spins up
tasks: 
  - before: docker build --file Dockerfile . --tag nginx-site:dev
    init: docker container run --name nginx-site-dev -p 80:80 nginx-site:dev

ports:
  - port: 80
    onOpen: open-preview