# Commands to start when Gitpod spins up
tasks: 
  - before: docker build --file Dockerfile . --tag nginx-site:dev
    command: docker run --name nginx-site-dev -d -p 0.0.0.0:443:443 nginx-site:dev
ports:
  - port: 443
    onOpen: open-preview
