# Commands to start when Gitpod spins up
tasks:
  - init: docker
    command: build . --file Dockerfile --tag nginx-site:dev-$(date +%s)
  - init: docker
    command: container run -d --name test-nginx run -d -p 80:80 nginx-site:dev-$(date +%s)

ports:
  - port: 80
    onOpen: open-preview