# Commands to start when Gitpod spins up
tasks:
  - init: "build_image"
    command: docker build . --file Dockerfile --tag nginx-site:dev-$(date +%s)
  - init: "run_image"
    command: docker container run -d --name test-nginx run -d -p 80:80 nginx-site:dev-$(date +%s)

ports:
  - port: 80
    onOpen: open-preview